### ISSUE TITLE
Does not work with flask-marshmallow 0.15

### ISSUE THREAD

**Issue by kattjevfel** [kynikos/lib.py.flask-rip#1]
Not 100% sure this is a problem with flask-rip or wiki-monkey, but leaning towards flask-rip.

When upgrading python-flask-marshmallow to 0.15.0-1 on Arch Linux, wiki-monkey fails to start with the following traceback:
```
May 14 17:51:54 archCT systemd[69]: Started Wiki Monkey's database server.
May 14 17:51:56 archCT wiki-monkey[1915621]: Traceback (most recent call last):
May 14 17:51:56 archCT wiki-monkey[1915621]:   File "/usr/bin/wiki-monkey", line 33, in <module>
May 14 17:51:56 archCT wiki-monkey[1915621]:     sys.exit(load_entry_point('wiki-monkey==5.5.3', 'console_scripts', 'wiki-monkey')())
May 14 17:51:56 archCT wiki-monkey[1915621]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 14 17:51:56 archCT wiki-monkey[1915621]:   File "/usr/lib/python3.11/site-packages/wiki_monkey/main.py", line 205, in main
May 14 17:51:56 archCT wiki-monkey[1915621]:     app.run(default_configfile, base_conf, argparser.parse_args())
May 14 17:51:56 archCT wiki-monkey[1915621]:   File "/usr/lib/python3.11/site-packages/wiki_monkey/lib/app.py", line 134, in run
May 14 17:51:56 archCT wiki-monkey[1915621]:     models, api, static = _pre_run(True)
May 14 17:51:56 archCT wiki-monkey[1915621]:                           ^^^^^^^^^^^^^^
May 14 17:51:56 archCT wiki-monkey[1915621]:   File "/usr/lib/python3.11/site-packages/wiki_monkey/lib/app.py", line 53, in _pre_run
May 14 17:51:56 archCT wiki-monkey[1915621]:     from . import models, api, static
May 14 17:51:56 archCT wiki-monkey[1915621]:   File "/usr/lib/python3.11/site-packages/wiki_monkey/lib/api/__init__.py", line 34, in <module>
May 14 17:51:56 archCT wiki-monkey[1915621]:     api = API(app, base_method_path=IMPLICIT,
May 14 17:51:56 archCT wiki-monkey[1915621]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 14 17:51:56 archCT wiki-monkey[1915621]:   File "/usr/lib/python3.11/site-packages/flask_rip.py", line 93, in __init__
May 14 17:51:56 archCT wiki-monkey[1915621]:     self.ma = Marshmallow(app)
May 14 17:51:56 archCT wiki-monkey[1915621]:               ^^^^^^^^^^^^^^^^
May 14 17:51:56 archCT wiki-monkey[1915621]:   File "/usr/lib/python3.11/site-packages/flask_marshmallow/__init__.py", line 103, in __init__
May 14 17:51:56 archCT wiki-monkey[1915621]:     self.init_app(app)
May 14 17:51:56 archCT wiki-monkey[1915621]:   File "/usr/lib/python3.11/site-packages/flask_marshmallow/__init__.py", line 116, in init_app
May 14 17:51:56 archCT wiki-monkey[1915621]:     self.SQLAlchemySchema.OPTIONS_CLASS.session = db.session
May 14 17:51:56 archCT wiki-monkey[1915621]:                                                   ^^^^^^^^^^
May 14 17:51:56 archCT wiki-monkey[1915621]: AttributeError: '_SQLAlchemyState' object has no attribute 'session'
May 14 17:51:56 archCT systemd[69]: wiki_monkey.service: Main process exited, code=exited, status=1/FAILURE
May 14 17:51:56 archCT systemd[69]: wiki_monkey.service: Failed with result 'exit-code'.
```

Downgrading python-flask-marshmallow to 0.14.0-4 works, but is not ideal.

**Comment by kynikos** [comment]
Hi, thanks for reporting this :heart: 

Unfortunately this seems to be the problem: https://github.com/marshmallow-code/flask-marshmallow/issues/262

It looks like flask-marshmallow 0.15 now requires flask-sqlalchemy 3.x, but the Arch Linux repos still distribute flask-sqlalchemy 2.5.1, so releasing 0.15 broke the dependency :cry: 

Relevant commit: https://github.com/marshmallow-code/flask-marshmallow/pull/249/commits/339541e6d7ba39caa160613ab798b0145e940e0f

Do you have time to report the upstream bug to the Arch issue tracker? I'm so busy unfortunately... If you don't have any other installed packages that depend on python-flask-marshmallow, downgrading it to 0.14 seems the only solution until Arch distributes python-flask-sqlalchemy version 3 (and I really really pray that that won't in turn break the wiki-monkey server... backward-incompatible library upgrades are a developer's nightmare :face_exhaling:).

**Comment by kattjevfel** [comment]
Since the Arch issue tracker disallows reports about outdated packages, the only solution is to wait. Luckily this is the only package requiring flask-marshmallow, so I'll be fine for now.
